import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF' },

  /* MAP SECTION */
  mapContainer: {
    height: '55%',
    width: '100%',
    backgroundColor: '#F1F5F9',
  },
  floatingActions: {
    position: 'absolute',
    right: 20,
    bottom: 40,
    zIndex: 10,
  },
  circleBtn: {
    width: 45,
    height: 45,
    borderRadius: 28,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },

  /* BOTTOM SHEET SECTION (20%) */
  bottomSheet: {
    flex: 1,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -25, // Tumpang tindih sedikit agar estetik
    paddingHorizontal: 24,
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E2E8F0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 15,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  unitCount: { fontSize: 12, color: '#94A3B8', fontWeight: '600' },
  scrollPadding: { paddingBottom: 120 },

  /* CARDS */
  unitCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  selectedCard: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
  iconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  selectedIconBox: { backgroundColor: 'rgba(255,255,255,0.2)' },
  infoBox: { flex: 1 },
  unitName: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
  unitDist: { fontSize: 11, color: '#64748B', marginTop: 2 },
  whiteText: { color: '#FFF' },
  lightText: { color: 'rgba(255,255,255,0.5)' },

  /* MODAL FILTER */
  filterOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.6)',
    justifyContent: 'flex-end',
  },
  filterSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterTitle: { fontSize: 20, fontWeight: '800', color: '#0F172A' },
  filterSubtitle: { fontSize: 14, color: '#94A3B8', marginVertical: 10 },
  closeText: { color: '#64748B', fontWeight: '700' },
  filterOptionsContainer: { marginVertical: 15 },
  filterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  filterItemActive: { borderColor: '#0F172A' },
  filterCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxActive: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
  checkboxInner: {
    width: 8,
    height: 8,
    backgroundColor: '#FFF',
    borderRadius: 2,
  },
  filterText: { fontSize: 15, fontWeight: '600', color: '#475569' },
  filterTextActive: { color: '#0F172A' },
  filterActions: { flexDirection: 'row', gap: 12, marginTop: 10 },
  filterReset: { flex: 1, paddingVertical: 16, alignItems: 'center' },
  resetText: { color: '#94A3B8', fontWeight: '700' },
  filterApply: {
    flex: 2,
    backgroundColor: '#0F172A',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  applyText: { color: '#FFF', fontWeight: '800' },
});
