export const PANDUAN_ICON_MAP: Record<number, any> = {
  1: require('../assets/iconsPanduan/earthquake_6348359.png'), 
  2: require('../assets/iconsPanduan/burning-house_1280950.png'), 
  3: require('../assets/iconsPanduan/flood_7028424.png'), 
  4: require('../assets/iconsPanduan/tsunami_6793283.png'),
  5: require('../assets/iconsPanduan/demonstration_8303342.png'), 
  6: require('../assets/iconsPanduan/image-removebg-preview (6).png'), 
  7: require('../assets/iconsPanduan/alert_4944314.png'),
  9: require('../assets/iconsPanduan/accident_4852381.png'), 
  10: require('../assets/iconsPanduan/image-removebg-preview.png'), 
  11: require('../assets/iconsPanduan/image-removebg-preview (1).png'), 
  12: require('../assets/iconsPanduan/image-removebg-preview (2).png'), 
  13: require('../assets/iconsPanduan/image-removebg-preview (4).png'), 
  16: require('../assets/iconsPanduan/flash-flood_17618621.png'),
};
