import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  mainWrapper: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    paddingTop: 75,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 25,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0F172A',
  },
  headerSub: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 4,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 15,
  },
  readOnlyContainer: {
    backgroundColor: '#F1F5F9',
    borderRadius: 16,
    padding: 15,
  },
  readOnlyRow: {
    paddingVertical: 5,
  },
  readOnlyLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  readOnlyValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 8,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
    marginBottom: 8,
    marginLeft: 4,
  },
  selector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  selectorText: {
    fontSize: 15,
    color: '#1E293B',
    fontWeight: '600',
  },
  placeholder: {
    color: '#94A3B8',
    fontWeight: '400',
  },
  chevron: {
    fontSize: 10,
    color: '#94A3B8',
  },
  errorBorder: {
    borderColor: '#EF4444',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 5,
    marginLeft: 5,
  },
  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDFA',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  locationText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0D9488',
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
  },
  toggleSub: {
    fontSize: 12,
    color: '#94A3B8',
  },
  photoContainer: {
    marginTop: 15,
  },
  uploadBox: {
    height: 180,
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    overflow: 'hidden',
  },
  uploadPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadText: {
    marginTop: 8,
    color: '#64748B',
    fontWeight: '600',
    fontSize: 13,
  },
  photoPreview: {
    width: '100%',
    height: '100%',
  },
  removePhoto: {
    textAlign: 'center',
    color: '#EF4444',
    fontWeight: '700',
    marginTop: 10,
    fontSize: 13,
  },
  btnSubmit: {
    backgroundColor: '#00A39D',
    padding: 18,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#00A39D',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  btnSubmitText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '800',
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  sheetContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 25,
    maxHeight: '80%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E2E8F0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 15,
    color: '#0F172A',
  },
  sheetItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  sheetItemActive: {
    backgroundColor: '#F0FDFA',
  },
  sheetItemText: {
    fontSize: 16,
    color: '#475569',
    fontWeight: '500',
  },
  sheetItemTextActive: {
    color: '#00A39D',
    fontWeight: '700',
  },
  checkIcon: {
    color: '#00A39D',
    fontWeight: 'bold',
  },
  sheetCloseBtn: {
    marginTop: 15,
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 15,
  },
  sheetCloseText: {
    fontWeight: '700',
    color: '#64748B',
  },
  alertOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    padding: 30,
  },
  alertCard: {
    backgroundColor: '#FFF',
    borderRadius: 25,
    padding: 25,
    alignItems: 'center',
  },
  alertTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 10,
  },
  alertMsg: {
    textAlign: 'center',
    color: '#64748B',
    lineHeight: 20,
    marginBottom: 20,
  },
  alertBtn: {
    backgroundColor: '#0F172A',
    width: '100%',
    padding: 15,
    borderRadius: 15,
    alignItems: 'center',
  },
  alertBtnText: {
    color: '#FFF',
    fontWeight: '700',
  },
});
