<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MBencanaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('m_bencana')->insert([
            // ================= BENCANA =================
            [
                'mbe_nama' => 'Gempa Bumi',
                'mbe_warna' => 'turquoise',
                'mbe_icon' => 'globe',
                'mbe_sort' => 1,
                'mbe_status' => 1,
                'mbe_visitor' => 245,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Kebakaran',
                'mbe_warna' => 'red',
                'mbe_icon' => 'fire',
                'mbe_sort' => 2,
                'mbe_status' => 1,
                'mbe_visitor' => 46,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Banjir',
                'mbe_warna' => 'blue',
                'mbe_icon' => 'tint',
                'mbe_sort' => 3,
                'mbe_status' => 1,
                'mbe_visitor' => 94,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Tsunami',
                'mbe_warna' => 'yellow',
                'mbe_icon' => 'warning-sign',
                'mbe_sort' => 4,
                'mbe_status' => 1,
                'mbe_visitor' => 56,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Demonstrasi',
                'mbe_warna' => 'darktor',
                'mbe_icon' => 'group',
                'mbe_sort' => 5,
                'mbe_status' => 1,
                'mbe_visitor' => 46,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Ancaman Bom',
                'mbe_warna' => 'pink',
                'mbe_icon' => 'time',
                'mbe_sort' => 6,
                'mbe_status' => 1,
                'mbe_visitor' => 36,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Gangguan Utilitas',
                'mbe_warna' => 'green',
                'mbe_icon' => 'home',
                'mbe_sort' => 7,
                'mbe_status' => 1,
                'mbe_visitor' => 36,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Sengatan Listrik',
                'mbe_warna' => 'orange',
                'mbe_icon' => 'bolt',
                'mbe_sort' => 8,
                'mbe_status' => 1,
                'mbe_visitor' => 37,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Banjir Bandang',
                'mbe_warna' => 'blue',
                'mbe_icon' => 'glass',
                'mbe_sort' => 9,
                'mbe_status' => 1,
                'mbe_visitor' => 15,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Letusan Gunung',
                'mbe_warna' => 'green',
                'mbe_icon' => 'fire',
                'mbe_sort' => 10,
                'mbe_status' => 0,
                'mbe_visitor' => 8,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Tanah Longsor',
                'mbe_warna' => 'choco',
                'mbe_icon' => 'circle-arrow-down',
                'mbe_sort' => 11,
                'mbe_status' => 0,
                'mbe_visitor' => 8,
                'mbe_bencana' => 1,
            ],
            [
                'mbe_nama' => 'Angin Besar',
                'mbe_warna' => 'turquoise',
                'mbe_icon' => 'cloud',
                'mbe_sort' => 12,
                'mbe_status' => 0,
                'mbe_visitor' => 7,
                'mbe_bencana' => 1,
            ],

            // ================= INFORMASI =================
            [
                'mbe_nama' => 'Informasi APAR',
                'mbe_warna' => 'darkblue',
                'mbe_icon' => 'info-sign',
                'mbe_sort' => 20,
                'mbe_status' => 1,
                'mbe_visitor' => 43,
                'mbe_bencana' => 0,
            ],
            [
                'mbe_nama' => 'Titik Kumpul Aman',
                'mbe_warna' => 'gray',
                'mbe_icon' => 'map-marker',
                'mbe_sort' => 21,
                'mbe_status' => 1,
                'mbe_visitor' => 39,
                'mbe_bencana' => 0,
            ],
            [
                'mbe_nama' => 'Prosedur Evakuasi',
                'mbe_warna' => 'choco',
                'mbe_icon' => 'flag',
                'mbe_sort' => 22,
                'mbe_status' => 1,
                'mbe_visitor' => 37,
                'mbe_bencana' => 0,
            ],
            [
                'mbe_nama' => 'Kontak Darurat',
                'mbe_warna' => 'orangelime',
                'mbe_icon' => 'phone-sign',
                'mbe_sort' => 23,
                'mbe_status' => 1,
                'mbe_visitor' => 51,
                'mbe_bencana' => 0,
            ],

            // ================= IT / INFRA =================
            [
                'mbe_nama' => 'Cyber IT',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 30,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Application',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 31,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Data Center (DC)',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 32,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Data Recovery Center (DRC)',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 33,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Network',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 34,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Infrastruktur Internal',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 35,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
            [
                'mbe_nama' => 'Kelistrikan Data Center',
                'mbe_warna' => null,
                'mbe_icon' => null,
                'mbe_sort' => 36,
                'mbe_status' => 1,
                'mbe_visitor' => 0,
                'mbe_bencana' => 2,
            ],
        ]);
    }
}
